console.log("Exercise 01: Variables and operators.");
console.log();
var numA1 = 1;
var numA2 = 2;
console.log(numA1 + numA2);
var stringB1 = "Spider";
var stringB2 = "man";
console.log(stringB1 + stringB2);
var stringC1 = "Brhadaranyakopanishadvivekachudamani";
var stringC2 = "Erreh Muñoz Castillo";
console.log(stringC1.length + stringC2.length);