console.log("Exercise 01: Variables and operators.");
console.log();
var num1a1 = 1;
var num1a2 = 2;
var sum = num1a1 + num1a2;
console.log("a: " + sum);
var string1b1 = "Spider";
var string1b2 = "man";
var concat = string1b1 + string1b2;
console.log("b: " + concat);
var string1c1 = "Brhadaranyakopanishadvivekachudamani";
var string1c2 = "Erreh Muñoz Castillo";
var sumLength = string1c1.length + string1c2.length;
console.log("c: " + sumLength);
console.log("Exercise 02: Strings.");
var string2a1 = "Do you want to log in?";
var string2a1 = string2a1.toUpperCase();
console.log("a: " + string2a1);
var string2b1 = "I can't finish this sentence.";
var string2b2 = string2b1.substring(0, 5);
console.log("b: " + string2b2);
var string2c1 = "something.js";
var string2c2 = string2c1.substring(string2c1.length - 3, string2c1.length);
console.log("c: "+ string2c2)