console.log("Exercise 01: Variables and operators.");
var x = 1;
var y = 2;
console.log(x + y);
var stringA = "Spider";
var stringB = "man";
console.log(stringB1 + stringB2);
var stringA = "Brhadaranyakopanishadvivekachudamani";
var stringB = "Erreh Muñoz Castillo";
console.log(stringA.length + stringB.length);